### PR TITLE
Implement archive extraction on Windows

### PR DESCRIPTION
**Pull request by iamakulov**
Should fix https://github.com/vladikoff/node-geckodriver/issues/6#issuecomment-241815139 (which I also experienced).

### CODE REVIEW

**Comment by vladikoff** [comment]
Thanks!

**Comment by Standard8** [comment]
@vladikoff Could we get a new release with this included please? I think it might fix an issue I'm having using this on Windows.

**Comment by vladikoff** [comment]
@Standard8 added in 1.1.3, let me know how it works out!

**Comment by Standard8** [comment]
> @Standard8 added in 1.1.3, let me know how it works out!

It works great, no problems now. Thank you @vladikoff and @iamakulov

**Pull request merged**
